[package]
name = "ddirs"
version = "0.1.0"
edition = "2021"

[lib]
name = "ddirs"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
